spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/bootdb
    username: spring-user
    password: secret
server:
  port: 8081
application:
  stockmanager:
    host: ${STOCK_MANAGER_HOST:localhost}
    port: ${STOCK_MANAGER_PORT:8080}
  stockquotemanager:
    host: ${STOCK_QUOTE_MANAGER_HOST:localhost}
    port: ${STOCK_QUOTE_MANAGER_PORT:8081}
